[build]
  command = "CI= npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  /api/* http://blogspringbootmysqlkotlin-env.eba-vpdedufk.ap-southeast-2.elasticbeanstalk.com/:splat 200
  /* /index.html 200
