[build]
  command = "CI= npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://kotlin-springboot-maven-blog-api-white-water-7328.fly.dev/api/articles:splat"
  status = 200
  force = true
