[build]
  command = "CI= npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/articles/*"
  to = "http://blogspringbootmysqlkotlin-env.eba-vpdedufk.ap-southeast-2.elasticbeanstalk.com/api/articles/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/articles/*"
  to = "http://blogspringbootmysqlkotlin-env.eba-vpdedufk.ap-southeast-2.elasticbeanstalk.com/api/articles/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
