[build]
  command = "CI= npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://nang-blog.onrender.com/api/articles:splat"
  status = 200
  force = true
